### Project specific config ###
environment:
  RECRUE_TEST_PACKAGES:
  SOLDAT_LINT_WITH_BUNDLED_NODE: "true"

  matrix:
  - SOLDAT_CHANNEL: stable
  - SOLDAT_CHANNEL: beta

### Generic setup follows ###
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DavidLemarier/ci/master/build-package.ps1'))

branches:
  only:
    - master

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
